### ISSUE TITLE
SonataCacheBundle-Unrecognized options “caches” under “sonata_cache”

### ISSUE THREAD

**Issue by sandeep-maurya** [sonata-project/SonataCacheBundle#42]
To use the CacheBundle, I have added the following lines to app/config/config.yml file.

```
sonata_cache:

caches:

esi:
    token: an unique security key # a random one is generated by default
    servers:
        - varnishadm -T 127.0.0.1:2000 {{ COMMAND }} "{{ EXPRESSION }}"

ssi:
    token: an unique security key # a random one is generated by default

mongo:
    database:   cache
    collection: cache
    servers:
        - {host: 127.0.0.1, port: 27017, user: username, password: pASS'}
        - {host: 127.0.0.2}

memcached:
    prefix: test     # prefix to ensure there is no clash between instances
    servers:
        - {host: 127.0.0.1, port: 11211, weight: 0}

apc:
    token:  s3cur3   # token used to clear the related cache
    prefix: test     # prefix to ensure there is no clash between instances
    servers:
        - { domain: kooqit.local, ip: 127.0.0.1, port: 80}
```

but it shows error while running the project...I dont know whats going wrong...

Error:

```
   [Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]
   Unrecognized options "caches" under "sonata_cache"
```

Any help will be appreciable...Thanks in advance
