### ISSUE TITLE
SSI error, please define a controller key

### ISSUE THREAD

**Issue by anton-kasperovich** [sonata-project/SonataCacheBundle#58]
I try to use SonataBlockBundle with SonataCacheBundle. After documentation reading and setting up all described steps, i got that error:

```
An exception has been thrown during the rendering of a template ("Please define a controller key") in CatalogBundle::index.html.twig at line 34.
```

My configuration:

``` yml
# config.yml
sonata_cache:
    caches:
        ssi:
            token: 'superprivatetoken'

sonata_block:
    default_contexts: [cms]
    blocks:
        block.search: ~
        block.popular.products:
            cache: sonata.cache.ssi
```

``` yml
#routing.yml
sonata_cache_cache:
    resource: '@SonataCacheBundle/Resources/config/routing/cache.xml'
    prefix: /
    options: { i18n: false }
```

``` php
# PopularProductsBlockService.php
class PopularProductsBlockService extends BaseBlockService
{
    public function __construct($name, EngineInterface $templating, DocumentManager $documentManager)
    {
        $this->name = $name;
        $this->templating = $templating;
        $this->documentManager = $documentManager;
    }

    /**
     * {@inheritdoc}
     */
    public function execute(BlockContextInterface $blockContext, Response $response = null)
    {
        $limit = 15; // @TODO: limit from settings.

        $items = $this->documentManager
            ->getRepository('ProductBundle:Product')
            ->findMostViewed($limit)
        ;

        return $this->renderResponse(
            $blockContext->getTemplate(),
            array(
                'items'         => $items,
                'block'         => $blockContext->getBlock(),
                'block_context' => $blockContext,
            ),
            $response
        );
    }
```

``` html
# index.html.twig
{{ sonata_block_render({ 'type': 'block.popular.products' }) }}
```
